import { Metadata } from 'next';
import Footer from './src/components/navigation/footer';
import Header from './src/components/navigation/header';
import './globals.css';
import { Inter } from 'next/font/google';
import { UserProvider } from './src/contexts/user';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
      <UserProvider>
          <Header />
          <main className="flex-grow">{children}</main>
          <Footer />
      </UserProvider>
      </body>
    </html>
  );
}
