version: '3.8'

name: skattabc-test

services:
  postgres-test:
    image: postgres:15
    environment:
      - POSTGRES_DB=ask_me_skattabc_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
    ports:
      - '5434:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
