version: '3.8'

services:
  postgres-dev:
    build: .
    container_name: skattabc-postgres-dev
    environment:
      POSTGRES_DB: ask_me_skattabc_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"  # Use 5433 to avoid conflicts with production proxy
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: