app = "skatt-abc-db-dev"
primary_region = "arn"

[build]

[env]
  POSTGRES_USER = "postgres"
  POSTGRES_DB = "ask_me_skattabc_dev"

[[mounts]]
  source = "pg_data"
  destination = "/var/lib/postgresql/data"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5432
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["pg_tls"]
    port = 5432

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"