name: Fly Deploy skatteabc
on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy skatteabc
    runs-on: ubuntu-latest
    concurrency: deploy-group
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy with Fly.io
        run: |
          flyctl deploy --remote-only \
            --build-secret ELASTICSEARCH_URL=${{ secrets.ELASTICSEARCH_URL }} \
            --build-secret OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-secret ELASTIC_PASSWORD=${{ secrets.ELASTIC_PASSWORD }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
