name: PostgreSQL Migrations

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Migration action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
        - deploy
        - status
        - reset
jobs:
  migrate:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run migration action
      run: |
        case "${{ github.event.inputs.action || 'deploy' }}" in
          "deploy")
            echo "Running Prisma migration deploy..."
            npx prisma migrate deploy
            ;;
          "status")
            echo "Checking migration status..."
            npx prisma migrate status
            ;;
          "reset")
            echo "Resetting database (use with caution)..."
            npx prisma migrate reset --force
            ;;
        esac
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}